#Reward Day : Reward
1: oak_wood 5
2: oak_wood 10
3: bread 10
4: leather_leggings 1
5: stone_sword 1
6: iron_pickaxe 1
7: iron_ingot 5
8: iron_ingot 10
9: iron_sword 1
10: iron_chestplate 1
11: iron_helmet 1
12: iron_leggings 1
13: iron_boots 1
14: iron_shovel 1
15: gold_ingot 5
16: lapis_lazuli 32
17: gold_ingot 10
18: lapis_lazuli 32
19: iron_ingot 32
20: anvil 1
21: diamond 1
22: diamond 2
23: diamond_sword 1
24: diamond_helmet 1
25: diamond_chestplate 1
26: diamond_leggings 1
27: diamond_boots 1
28: diamond_pickaxe 1
29: diamond 10
30: emerald 5
31: emerald_block 5
